name: TypeCheck

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - 'v[0-9]+.*'
      - '[0-9]+.x'

env:
  FORCE_COLOR: 1
  HEAD_COMMIT: ${{ github.sha }}
  CACHED_DEPENDENCY_PATHS: |
    ${{ github.workspace }}/node_modules
    ${{ github.workspace }}/apps/*/node_modules
    ${{ github.workspace }}/ghost/*/node_modules
    ${{ github.workspace }}/e2e/node_modules
  NX_REJECT_UNKNOWN_LOCAL_CACHE: 0
  NODE_VERSION: 22.18.0

concurrency:
  group: typecheck-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  job_setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      pull-requests: read
    steps:
      - name: Checkout current commit
        uses: actions/checkout@v4
        with:
          ref: ${{ env.HEAD_COMMIT }}
          fetch-depth: 2

      - name: Get metadata (push)
        if: github.event_name == 'push'
        run: |
          NUMBER_OF_COMMITS=$(printf "%s\n" '${{ toJson(github.event.commits.*.id) }}' | jq length)
          echo "There are $NUMBER_OF_COMMITS commits in this push."
          echo "BASE_COMMIT=$(git rev-parse HEAD~$NUMBER_OF_COMMITS)" >> $GITHUB_ENV

      - name: Get metadata (pull_request)
        if: github.event_name == 'pull_request'
        run: |
          BASE_COMMIT=$(curl --location --request GET 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}' --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r .base.sha)
          echo "Setting BASE_COMMIT to $BASE_COMMIT"
          echo "BASE_COMMIT=$BASE_COMMIT" >> $GITHUB_ENV

      - name: Determine changed packages
        uses: AurorNZ/paths-filter@v4.0.0
        id: changed
        with:
          filters: |
            any-ts:
              - '**/*.ts'
              - '**/*.tsx'
              - '**/tsconfig*.json'
              - 'package.json'
              - 'yarn.lock'

      - name: Compute lockfile hash
        run: echo "hash=lockfile-${{ hashFiles('yarn.lock') }}" >> "$GITHUB_ENV"

      - name: Compute dependency cache key
        run: echo "cachekey=dep-cache-${{ hashFiles('yarn.lock') }}-${{ env.HEAD_COMMIT }}" >> "$GITHUB_ENV"

      - name: Nx cache
        uses: actions/cache@v4
        id: cache_nx
        with:
          path: .nxcache
          key: nx-Linux-${{ github.ref }}-${{ env.HEAD_COMMIT }}
          restore-keys: |
            nx-Linux-${{ github.ref }}-${{ env.HEAD_COMMIT }}
            nx-Linux-${{ github.ref }}
            nx-Linux

      - name: Check dependency cache
        uses: actions/cache@v4
        id: cache_dependencies
        with:
          path: ${{ env.CACHED_DEPENDENCY_PATHS }}
          key: ${{ env.cachekey }}

      - name: Set up Node
        uses: actions/setup-node@v4
        env:
          FORCE_COLOR: 0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: bash .github/scripts/install-deps.sh

    outputs:
      changed_any_ts: ${{ steps.changed.outputs.any-ts }}
      base_commit: ${{ env.BASE_COMMIT }}
      dependency_cache_key: ${{ env.cachekey }}

  job_typecheck:
    runs-on: ubuntu-latest
    needs: [job_setup]
    if: needs.job_setup.outputs.changed_any_ts == 'true'
    name: TypeScript Type Check
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1000

      - uses: actions/setup-node@v4
        env:
          FORCE_COLOR: 0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore caches
        uses: ./.github/actions/restore-cache
        env:
          DEPENDENCY_CACHE_KEY: ${{ needs.job_setup.outputs.dependency_cache_key }}

      - name: Nx cache
        uses: actions/cache@v4
        with:
          path: .nxcache
          key: nx-Linux-${{ github.ref }}-${{ env.HEAD_COMMIT }}
          restore-keys: |
            nx-Linux-${{ github.ref }}-${{ env.HEAD_COMMIT }}
            nx-Linux-${{ github.ref }}
            nx-Linux

      - name: Run TypeScript type checking
        run: yarn nx affected -t test:types --base=${{ needs.job_setup.outputs.base_commit }}

      - uses: tryghost/actions/actions/slack-build@main
        if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
